#include <hxcpp.h>

namespace hx {
const char *__hxcpp_all_files[] = {
#ifdef HXCPP_DEBUGGER
"F:\\development\\resource\\platform\\haxe\\3_1_3\\haxe\\std/cpp/Lib.hx",
"F:\\development\\resource\\platform\\haxe\\3_1_3\\haxe\\std/cpp/_std/Reflect.hx",
"F:\\development\\resource\\platform\\haxe\\3_1_3\\haxe\\std/cpp/_std/Std.hx",
"F:\\development\\resource\\platform\\haxe\\3_1_3\\haxe\\std/cpp/_std/Sys.hx",
"F:\\development\\resource\\platform\\haxe\\3_1_3\\haxe\\std/cpp/_std/Type.hx",
"F:\\development\\resource\\platform\\haxe\\3_1_3\\haxe\\std/haxe/Log.hx",
"F:\\development\\resource\\platform\\haxe\\3_1_3\\haxe\\std/haxe/Timer.hx",
"F:\\development\\resource\\platform\\haxe\\3_1_3\\haxe\\std/haxe/io/Eof.hx",
"Main.hx",
"haxor/component/Behaviour.hx",
"haxor/component/Component.hx",
"haxor/context/HaxorContext.hx",
"haxor/context/Process.hx",
"haxor/core/Application.hx",
"haxor/core/BaseApplication.hx",
"haxor/core/Console.hx",
"haxor/core/Engine.hx",
"haxor/core/Entity.hx",
"haxor/core/Resource.hx",
"haxor/core/Scene.hx",
"haxor/core/Time.hx",
"haxor/graphics/Screen.hx",
"haxor/platform/OSWindow.hx",
"haxor/platform/graphics/GraphicContext.hx",
"haxor/platform/graphics/Graphics.hx",
"haxor/platform/graphics/OpenGL.hx",
"haxor/platform/graphics/WinGL.hx",
"haxor/platform/windows/Entry.hx",
"haxor/platform/windows/WinApplication.hx",
"haxor/platform/windows/Window.hx",
#endif
 0 };

const char *__hxcpp_all_files_fullpath[] = {
#ifdef HXCPP_DEBUGGER
"F:\\development\\resource\\platform\\haxe\\3_1_3\\haxe\\std\\cpp\\Lib.hx",
"F:\\development\\resource\\platform\\haxe\\3_1_3\\haxe\\std\\cpp\\_std\\Reflect.hx",
"F:\\development\\resource\\platform\\haxe\\3_1_3\\haxe\\std\\cpp\\_std\\Std.hx",
"F:\\development\\resource\\platform\\haxe\\3_1_3\\haxe\\std\\cpp\\_std\\Sys.hx",
"F:\\development\\resource\\platform\\haxe\\3_1_3\\haxe\\std\\cpp\\_std\\Type.hx",
"F:\\development\\resource\\platform\\haxe\\3_1_3\\haxe\\std\\haxe\\Log.hx",
"F:\\development\\resource\\platform\\haxe\\3_1_3\\haxe\\std\\haxe\\Timer.hx",
"F:\\development\\resource\\platform\\haxe\\3_1_3\\haxe\\std\\haxe\\io\\Eof.hx",
"F:\\development\\project\\web\\thelab\\haxor_engine_1_0\\source\\Main.hx",
"F:\\development\\project\\web\\thelab\\haxor_engine_1_0\\source\\haxor\\component\\Behaviour.hx",
"F:\\development\\project\\web\\thelab\\haxor_engine_1_0\\source\\haxor\\component\\Component.hx",
"F:\\development\\project\\web\\thelab\\haxor_engine_1_0\\source\\haxor\\context\\HaxorContext.hx",
"F:\\development\\project\\web\\thelab\\haxor_engine_1_0\\source\\haxor\\context\\Process.hx",
"F:\\development\\project\\web\\thelab\\haxor_engine_1_0\\source\\haxor\\core\\Application.hx",
"F:\\development\\project\\web\\thelab\\haxor_engine_1_0\\source\\haxor\\core\\BaseApplication.hx",
"F:\\development\\project\\web\\thelab\\haxor_engine_1_0\\source\\haxor\\core\\Console.hx",
"F:\\development\\project\\web\\thelab\\haxor_engine_1_0\\source\\haxor\\core\\Engine.hx",
"F:\\development\\project\\web\\thelab\\haxor_engine_1_0\\source\\haxor\\core\\Entity.hx",
"F:\\development\\project\\web\\thelab\\haxor_engine_1_0\\source\\haxor\\core\\Resource.hx",
"F:\\development\\project\\web\\thelab\\haxor_engine_1_0\\source\\haxor\\core\\Scene.hx",
"F:\\development\\project\\web\\thelab\\haxor_engine_1_0\\source\\haxor\\core\\Time.hx",
"F:\\development\\project\\web\\thelab\\haxor_engine_1_0\\source\\haxor\\graphics\\Screen.hx",
"F:\\development\\project\\web\\thelab\\haxor_engine_1_0\\source\\haxor\\platform\\OSWindow.hx",
"F:\\development\\project\\web\\thelab\\haxor_engine_1_0\\source\\haxor\\platform\\graphics\\GraphicContext.hx",
"F:\\development\\project\\web\\thelab\\haxor_engine_1_0\\source\\haxor\\platform\\graphics\\Graphics.hx",
"F:\\development\\project\\web\\thelab\\haxor_engine_1_0\\source\\haxor\\platform\\graphics\\OpenGL.hx",
"F:\\development\\project\\web\\thelab\\haxor_engine_1_0\\source\\haxor\\platform\\graphics\\WinGL.hx",
"F:\\development\\project\\web\\thelab\\haxor_engine_1_0\\source\\haxor\\platform\\windows\\Entry.hx",
"F:\\development\\project\\web\\thelab\\haxor_engine_1_0\\source\\haxor\\platform\\windows\\WinApplication.hx",
"F:\\development\\project\\web\\thelab\\haxor_engine_1_0\\source\\haxor\\platform\\windows\\Window.hx",
#endif
 0 };

const char *__hxcpp_all_classes[] = {
#ifdef HXCPP_DEBUGGER
"haxor.core.Resource",
"haxor.component.Component",
"haxor.component.Behaviour",
"haxor.core.BaseApplication",
"haxor.platform.windows.WinApplication",
"haxor.core.Application",
"Main",
"Reflect",
"Std",
"cpp.Lib",
"Sys",
"Type",
"haxe.Log",
"haxe.Timer",
"haxe.io.Eof",
"haxor.context.HaxorContext",
"haxor.context.Process",
"haxor.core.Console",
"haxor.core.Engine",
"haxor.core.Entity",
"haxor.core.Scene",
"haxor.core.Time",
"haxor.graphics.Screen",
"haxor.platform.OSWindow",
"haxor.platform.graphics.GraphicContext",
"haxor.platform.graphics.WinGL",
"haxor.platform.graphics.OpenGL",
"haxor.platform.graphics.Graphics",
"haxor.platform.windows.Entry",
"haxor.platform.windows.Window",
#endif
 0 };
} // namespace hx
void __files__boot() { __hxcpp_set_debugger_info(hx::__hxcpp_all_classes, hx::__hxcpp_all_files_fullpath); }
